name: AI Code Review

on:
  pull_request:
    types: [opened, reopened, synchronize]
    branches: [master/*]

jobs:
  ai-code-review:
    name: AI Code Review
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name == github.repository  # 安全防护：仅处理本仓库PR
    
    permissions:
      contents: read     # 读取代码内容
      pull-requests: write  # 添加PR评论
      issues: write      # 必要权限（GitHub将PR评论视为issue范畴）

    steps:
      # 核心审查步骤
      - name: DeepSeek Review
        uses: guesspalm/deepseek-review@main
        with:
          chat-token: ${{ secrets.CHAT_TOKEN }} 
          github-token: ${{ secrets.GITHUB_TOKEN }}
          base-url: ${{ vars.CR_BASE_URL }}
          model: ${{ vars.CR_CHAT_MODEL }}
          include-patterns: ${{ vars.CR_INCLUDE_PATTERNS }}
          exclude-patterns: ${{ vars.CR_EXCLUDE_PATTERNS }}
          sys-prompt: ${{ vars.CR_SYS_PROMPT }}
          user-prompt: ${{ vars.CR_USER_PROMPT }}
          temperature: ${{ vars.CR_TEMPERATURE }}
          max-length: ${{ vars.CR_MAX_LENGTH }}
          reasoning-effort: ${{ vars.CR_REASONING_EFFORT }}
          reasoning-exclude: ${{ vars.CR_REASONING_EXCLUDE }}
